# Chunk type
if(VE_CHUNK_TYPE STREQUAL "CHUNK8")
    add_compile_definitions(VE_CHUNK_TYPE_8)
elseif(VE_CHUNK_TYPE STREQUAL "CHUNK16")
    add_compile_definitions(VE_CHUNK_TYPE_16)
elseif(VE_CHUNK_TYPE STREQUAL "CHUNK32")
    add_compile_definitions(VE_CHUNK_TYPE_32)
else()
    message(FATAL_ERROR "Invalid VE_CHUNK_TYPE: ${VE_CHUNK_TYPE}")
endif()